config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  root 'home#top'

  get 'home/top'
  get 'users/admin_index'
  get 'papers/admin_index'



  resources :users, only: [:edit, :update, :index, :destroy]do
  	member do
  		get :following, :followers, :my_list, :interest_list, :following_list
    end
  end
  resources :relationships, only: [:create, :destroy]

  delete '/users/:id' => 'users#destroy'

  resources :papers, only: [:new, :index, :show, :create, :destroy] do
  	resource :likes, only: [:create, :destroy]
  	resource :interests, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
	acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  default_scope -> { order(created_at: :desc) }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         attachment :user_image

         validates :name, presence: true, length: { maximum:12 }
         validates :email, presence: true, uniqueness: true
         validates :content, length: { maximum:297 }

         has_many :papers, dependent: :destroy

         has_many :interests, dependent: :destroy
         has_many :interested_papers, through: :interests, source: :paper

         has_many :likes, dependent: :destroy
         has_many :liked_papers, through: :likes, source: :paper

         has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
         has_many :followings, through: :following_relationships

         has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
         has_many :followers, through: :follower_relationships

        def following?(other_user)
          following_relationships.find_by(following_id: other_user.id)
        end

        def follow!(other_user)
          following_relationships.create!(following_id: other_user.id)
        end

        def unfollow!(other_user)
          following_relationships.find_by(following_id: other_user.id).destroy
        end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!, only:[:edit, :update]
	before_action :authenticate_admin!, only:[:admin_index]

	def my_list
		@user= User.find(params[:id])
		@papers = @user.papers.all
		@paper_images = PaperImage.all
	end

	def interest_list
		@user= User.find(params[:id])
		@paper_images = PaperImage.all
		if user_signed_in?
			if @user.id == current_user.id
			else
				redirect_to my_list_user_path(@user)
			end
		else
			redirect_to my_list_user_path(@user)
		end
	end

	def following_list
		@user= User.find(params[:id])
		@users = @user.followings
		@paper_images = PaperImage.all
		if user_signed_in?
			if @user.id == current_user.id
			else
				redirect_to my_list_user_path(@user)
			end
		else
			redirect_to my_list_user_path(@user)
		end
	end

	def following
		@user= User.find(params[:id])
		@users = @user.followings
		render 'following'
	end

	def followers
		@user= User.find(params[:id])
		@users = @user.followers
		render 'followers'
	end

	def edit
		@user= User.find(params[:id])
		if @user.id == current_user.id
		else
			redirect_to my_list_user_path(@user)
		end
	end

	def update
		@user= User.find(params[:id])
		if @user.id == current_user.id
			@user.update(user_params)
			redirect_to my_list_user_path(@user)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		if admin_signed_in?
			@user.destroy
			redirect_to users_admin_index_path
		elsif @user.id == current_user.id
			@user.destroy
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	def admin_index
		@users = User.all
	end


	private

	def user_params
		params.require(:user).permit(:name,:email,:privacy,:user_image,:content)
	end
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
		user == current_user
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<div  class="clearfix">
	<div  class=" profile_image">
		<span  class="paper_pin profile_image_pin"></span><span  class="paper_pin profile_image_pin2"></span>
		<%= attachment_image_tag @user, :user_image, :fill, 300, 300, format: 'jpeg', fallback: "no_image300x300.jpg" %>
	</div>
	<div  class="left">
		<%= render 'stats' %>
		<% if user_signed_in? %>
			<% if @user == current_user %>
				<%= link_to edit_user_path(@user.id) do %><div  class="pen"></div><% end %>
			<% else %>
				<%= render 'follow_form' %>
			<% end %>
		<% end %>
	</div>
	<div  class ="user_paper">
		<span  class="sero"></span>
		<h1  class="user_name"><%= @user.name %></h1>
		<p  class=" user_content"><%= @user.content %></p>
	</div>
</div>

<div class="collapse navbar-collapse" id="navbarEexample">
	<ul class="nav nav-tabs nav-justified">
		<% if user_signed_in? %>
			<% if @user.id == current_user.id %>
				<% if @path.is('users#my_list') %>
					<li role="presentation" class="active">
						<%= link_to "MYメモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% else %>
					<li role="presentation">
						<%= link_to "MYメモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% end %>
				<% if @path.is('users#interest_list') %>
					<li role="presentation" class="active">
						<%= link_to "気になるリスト", interest_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% else %>
					<li role="presentation">
						<%= link_to "気になるリスト", interest_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% end %>
				<% if @path.is('users#following_list') %>
					<li role="presentation" class="active">
						<%= link_to "フォロワーメモ", following_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% else %>
					<li role="presentation">
						<%= link_to "フォロワーメモ", following_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% end %>
			<% else %>
				<% if @path.is('users#my_list') %>
					<li role="presentation" class="active">
						<%= link_to "#{@user.name}メモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% else %>
					<li role="presentation">
						<%= link_to "#{@user.name}メモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% end %>
			<% end %>
			<% else %>
				<% if @path.is('users#my_list') %>
					<li role="presentation" class="active">
						<%= link_to "#{@user.name}メモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% else %>
					<li role="presentation">
						<%= link_to "#{@user.name}メモ", my_list_user_path(@user.id), class:"list_nav" %>
					</li>
				<% end %>
		<% end %>
	</ul>
</div>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div  class="stats">
<ul>
  <li>
    <div  class="h">
  <a href="<%= following_user_path(@user) %>">
      <%= @user.followings.count %>
    フォロー
  </a>
</div>
  </li>
  <li>
    <div  class="h h_b">
  <a href="<%= followers_user_path(@user) %>">
      <%= @user.followers.count %>
    フォロワー
  </a>
</div>
  </li>
</ul>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを解除する", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/admin_index.html.erb
<h1>ユーザー一覧</h1>
<table  class="table-hover table orange">
	<thead>
		<tr>
			<th>ユーザー画像</th>
			<th>ユーザー名</th>
			<th>自己紹介文</th>
			<th>メールアドレス</th>
			<th>フォロー数</th>
			<th>フォロワー数</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :user_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image100x100.jpg" %></td>
			<td><%= user.name %></td>
			<td><%= user.content %></td>
			<td><%= user.email %></td>
			<td><%= user.followings.count %></td>
			<td><%= user.followers.count %></td>
			<td><%= link_to "退会", user_path(user.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "本当に退会させますか？" %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/edit.html.erb
<div  class="clearfix">

	<% if @user.errors.any? %>
	<div id="error_explanation" class="alert alert-danger">
		<h2  class="alert_h2"><%= pluralize(@user.errors.count, "つ") %> のエラーがある為ユーザー内容を編集できません。</h2>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= form_for(@user) do |f| %>
	<div  class=" profile_image">
		<span  class="paper_pin profile_image_pin"></span><span  class="paper_pin profile_image_pin2"></span>
		<%= attachment_image_tag @user, :user_image, :fill, 300, 300, format: 'jpeg', fallback: "no_image300x300.jpg" %>
	</div>
	<%= f.attachment_field :user_image %>
	<div  class ="user_paper">
		<span  class="sero"></span>
		<h1  class="user_name"><%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "ユーザー名", class:"edit" %></h1>
		<p  class=" user_content"><%= f.text_area :content, autocomplete: "content", placeholder: "自己紹介文", class:"edit_content" %></p>
	</div>
	<div  class="user_d">
		<span  class="paper_pin pin_b"></span><span  class="paper_pin pin_y"></span>
		<P><%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "メールアドレス", class:"edit" %></P>
		<P><%= f.text_field :password, autocomplete: "off", placeholder: "新しいパスワードに変更", class:"edit" %></P>
		<P><%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "新しいパスワード確認", class:"edit" %></P>
	</div>
	<%= f.submit "", class:"pen", "data-confirm" => "この内容で変更しますか？" %>
	<% end %>
</div>

app/views/users/followers.html.erb
<%= render 'users/profile', users: @users %>

<div  class="clearfix">
	<h1>フォロワーリスト</h1>
	<% @user.followers.each do |user| %>

	<%= link_to my_list_user_path(user) do %>
	<div  class=" profile_image following_image">
		<span  class="paper_pin"></span>
		<%= attachment_image_tag user, :user_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image100x100.jpg" %>
		<span  class="h h_y"><p><%= user.name %></p></span>
	</div>
	<% end %>

	<% end %>
</div>

app/views/users/following.html.erb
<%= render 'users/profile', users: @users %>

<div  class="clearfix">
	<h1>フォローリスト</h1>
	<% @user.followings.each do |user| %>

	<%= link_to my_list_user_path(user) do %>
	<div  class=" profile_image following_image">
		<span  class="paper_pin"></span>
		<%= attachment_image_tag user, :user_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image100x100.jpg" %>
		<span  class="h h_y"><p><%= user.name %></p></span>
	</div>
	<% end %>

	<% end %>
</div>

app/views/users/following_list.html.erb
<%= render 'users/profile', users: @users %>

<div class="clearfix">
	<% @users.each do |user| %>
	<% @papers = Paper.where(user_id: user.id) %>
	<% @papers.each do |paper| %>
	<% if paper.genre_id == nil %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% elsif paper.genre_id == 3 %>
	<div  class="paper p_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id <= 4 %>
	<div  class="paper y_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id >= 9 %>
	<div  class="paper">
		<span  class="paper_pin pin_y"></span>
	<% else %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% end %>
		<h4><%= link_to paper_path(paper.id) do %><%= paper.title %><% end %></h4>
		<p  class="content"><%= link_to paper_path(paper.id) do %><%= paper.content %><% end %></p>
		<span  class="paper_date">
			<% unless paper.start_date.blank? %>
				<%= paper.start_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
			<% if paper.start_date.present? %>~
			<% elsif paper.end_date.present? %>~
			<% end %>
			<% unless paper.end_date.blank? %>
				<%= paper.end_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
		</span>
		<%# @paper_images.each do |pi| %>
		<%# if paper.id == pi.paper_id %>
			<%#= attachment_image_tag pi, :image, :fill, 300, 300, format: 'jpeg' %>
		<%# end %>
		<%# end %>
		<span  class="images">
			<% if paper.paper_images.count > 0 %>
				<span class="glyphicon glyphicon-camera blue" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% else %>
				<span class="glyphicon glyphicon-camera black" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% end %>
		</span>
		<span  class="likes">
			<% if user_signed_in? %>
				<% if current_user.likes.find_by(paper_id: paper.id) %>
					<%= link_to paper_likes_path(paper.id), method: :delete, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart red" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% else %>
					<%= link_to paper_likes_path(paper.id), method: :post, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% end %>
				<% if current_user.interests.find_by(paper_id: paper.id) %>
					<%= link_to paper_interests_path(paper.id), method: :delete, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark green" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% else %>
					<%= link_to paper_interests_path(paper.id), method: :post, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% end %>
			<% else %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
			<% end %>
		</span>
		<%= link_to my_list_user_path(paper.user_id) do %><span  class="paper_user_image"><%= attachment_image_tag paper.user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image50x50.jpg", class:"maru" %><%= paper.user.name %></span><% end %>
	</div>
	<% end %>
	<% end %>
</div>

app/views/users/interest_list.html.erb
<%= render 'users/profile', users: @users %>

<div class="clearfix">
	<% @user.interested_papers.each do |paper| %>
	<% if paper.genre_id == nil %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% elsif paper.genre_id == 3 %>
	<div  class="paper p_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id <= 4 %>
	<div  class="paper y_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id >= 9 %>
	<div  class="paper">
		<span  class="paper_pin pin_y"></span>
	<% else %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% end %>
		<h4><%= link_to paper_path(paper.id) do %><%= paper.title %><% end %></h4>
		<p  class="content"><%= link_to paper_path(paper.id) do %><%= paper.content %><% end %></p>
		<span  class="paper_date">
			<% unless paper.start_date.blank? %>
				<%= paper.start_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
			<% if paper.start_date.present? %>~
			<% elsif paper.end_date.present? %>~
			<% end %>
			<% unless paper.end_date.blank? %>
				<%= paper.end_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
		</span>
		<%# @paper_images.each do |pi| %>
		<%# if paper.id == pi.paper_id %>
			<%#= attachment_image_tag pi, :image, :fill, 300, 300, format: 'jpeg' %>
		<%# end %>
		<%# end %>
		<span  class="images">
			<% if paper.paper_images.count > 0 %>
				<span class="glyphicon glyphicon-camera blue" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% else %>
				<span class="glyphicon glyphicon-camera black" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% end %>
		</span>
		<span  class="likes">
			<% if user_signed_in? %>
				<% if current_user.likes.find_by(paper_id: paper.id) %>
					<%= link_to paper_likes_path(paper.id), method: :delete, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart red" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% else %>
					<%= link_to paper_likes_path(paper.id), method: :post, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% end %>
				<% if current_user.interests.find_by(paper_id: paper.id) %>
					<%= link_to paper_interests_path(paper.id), method: :delete, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark green" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% else %>
					<%= link_to paper_interests_path(paper.id), method: :post, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% end %>
			<% else %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
			<% end %>
		</span>
		<%= link_to my_list_user_path(paper.user_id) do %><span  class="paper_user_image"><%= attachment_image_tag paper.user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image50x50.jpg", class:"maru" %><%= paper.user.name %></span><% end %>
	</div>
	<% end %>
</div>

app/views/users/my_list.html.erb
<%= render 'users/profile', users: @users %>

<div class="clearfix">
	<% @papers.each do |paper| %>
	<% if paper.genre_id == nil %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% elsif paper.genre_id == 3 %>
	<div  class="paper p_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id <= 4 %>
	<div  class="paper y_paper">
		<span  class="paper_pin"></span>
	<% elsif paper.genre_id >= 9 %>
	<div  class="paper">
		<span  class="paper_pin pin_y"></span>
	<% else %>
	<div  class="paper b_paper">
		<span  class="paper_pin pin_b"></span>
	<% end %>
		<h4><%= link_to paper_path(paper.id) do %><%= paper.title %><% end %></h4>
		<p  class="content"><%= link_to paper_path(paper.id) do %><%= paper.content %><% end %></p>
		<span  class="paper_date">
			<% unless paper.start_date.blank? %>
				<%= paper.start_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
			<% if paper.start_date.present? %>~
			<% elsif paper.end_date.present? %>~
			<% end %>
			<% unless paper.end_date.blank? %>
				<%= paper.end_date.strftime("%Y年%-m月%-d日") %>
			<% end %>
		</span>
		<%# @paper_images.each do |pi| %>
		<%# if paper.id == pi.paper_id %>
			<%#= attachment_image_tag pi, :image, :fill, 300, 300, format: 'jpeg' %>
		<%# end %>
		<%# end %>
		<span  class="images">
			<% if paper.paper_images.count > 0 %>
				<span class="glyphicon glyphicon-camera blue" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% else %>
				<span class="glyphicon glyphicon-camera black" aria-hidden="true"><%= paper.paper_images.count %></span>
			<% end %>
		</span>
		<span  class="likes">
			<% if user_signed_in? %>
				<% if current_user.likes.find_by(paper_id: paper.id) %>
					<%= link_to paper_likes_path(paper.id), method: :delete, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart red" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% else %>
					<%= link_to paper_likes_path(paper.id), method: :post, id: "likes_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<% end %>
				<% if current_user.interests.find_by(paper_id: paper.id) %>
					<%= link_to paper_interests_path(paper.id), method: :delete, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark green" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% else %>
					<%= link_to paper_interests_path(paper.id), method: :post, id: "interests_#{paper.id}", remote: true do %>
					<span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
				<% end %>
			<% else %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-heart black" aria-hidden="true"><%= paper.likes.count %></span><% end %>
				<%= link_to new_user_session_path do %><span class="glyphicon glyphicon-bookmark black" aria-hidden="true"><%= paper.interests.count %></span><% end %>
			<% end %>
		</span>
		<%= link_to my_list_user_path(paper.user_id) do %><span  class="paper_user_image"><%= attachment_image_tag paper.user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image50x50.jpg", class:"maru" %><%= paper.user.name %></span><% end %>
	</div>
	<% end %>
</div>