config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

  root 'home#top'

  get 'home/top'
  get 'users/admin_index'
  get 'papers/admin_index'



  resources :users, only: [:edit, :update, :index, :destroy]do
  	member do
  		get :following, :followers, :my_list, :interest_list, :following_list
    end
  end
  resources :relationships, only: [:create, :destroy]

  delete '/users/:id' => 'users#destroy'

  resources :papers, only: [:new, :index, :show, :create, :destroy] do
  	resource :likes, only: [:create, :destroy]
  	resource :interests, only: [:create, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScratchPaper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <header>
    <nav class="navbar">
      <%= link_to home_top_path, class:"navbar-brand" do %>
        <div class="navbar-header scratch_paper_logo">
          <span  class="sero"></span>
          Scratch
        </div>
        <div class="navbar-header scratch_paper_logo logo2">
          <span  class="sero"></span>
          Paper
        </div>
        <% end %>
      <div class="collapse navbar-collapse" id="navbarEexample">
        <ul class="nav navbar-right nav-pills">
          <% if admin_signed_in? %>
            <li role="presentation">
              <% if @path.is('papers#admin_index') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to papers_admin_index_path do %><span  class="tag_pin"></span><P  class="length">投稿一覧</P><% end %></button>
            </li>
            <li role="presentation">
              <% if @path.is('users#admin_index') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to users_admin_index_path do %><span  class="tag_pin"></span><P  class="length">ユーザー一覧</P><% end %></button>
            </li>
            <li role="presentation" >
              <button type="button" class="navbar-btn tag tag_w"><%= link_to destroy_admin_session_path, method: :delete do %><span  class="tag_pin"></span><P  class="length">ログアウト</P><% end %></button>
            </li>
          <% else %>
            <% if user_signed_in? %>
            <li role="presentation">
              <% if @path.is('papers#index') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to papers_path do %><span  class="tag_pin"></span><P  class="length">投稿一覧</P><% end %></button>
            </li>
            <li role="presentation">
              <% if @path.is('papers#new') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag tag_w">
              <% end %>
              <%= link_to new_paper_path do %><span  class="tag_pin"></span><P  class="length">新規投稿</P><% end %></button>
            </li>
            <li role="presentation">
              <% if @path.is('users')%>
                <% if @user.id == current_user.id %>
                  <button type="button" class="navbar-btn tag tag_p">
                <% else %>
                  <button type="button" class="navbar-btn tag">
                <% end %>
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to my_list_user_path(current_user.id) do %><span  class="tag_pin"></span><P  class="length">マイページ</P><% end %></button>
            </li>
            <li role="presentation" >
              <button type="button" class="navbar-btn tag tag_w"><%= link_to destroy_user_session_path, method: :delete do %><span  class="tag_pin"></span><P  class="length">ログアウト</P><% end %></button>
            </li>
            <% else %>
            <li role="presentation">
              <% if @path.is('papers#index') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to papers_path do %><span  class="tag_pin"></span><P  class="length">投稿一覧</P><% end %></button>
            </li>
            <li role="presentation">
              <% if @path.is('users/sessions#new') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag tag_w">
              <% end %>
              <%= link_to new_user_session_path do %><span  class="tag_pin"></span><P  class="length">ログイン</P><% end %></button>
            </li>
            <li role="presentation">
              <% if @path.is('users/registrations#new') %>
              <button type="button" class="navbar-btn tag tag_p">
              <% else %>
              <button type="button" class="navbar-btn tag">
              <% end %>
              <%= link_to new_user_registration_path do %><span  class="tag_pin"></span><P  class="length">新規登録</P><% end %></button>
            </li>
            <% end %>
          <% end %>
        </ul>
    </nav>
  </header>
  <body>
    <div  class="box">
     <%= yield %>
    </div>
  </body>
  <footer>
    <span>&#169; ScratchPaper.</span>
  </footer>
</html>